#let title = "Hijri Week Calendar"
#let subtitle = "A Hijri counterpart of the ISO 8601 calendar"
#let keywords = ("Hijri", "ISO 8601", "Calendars", "Week date", "Datekeeping", "Islamic calendar", "Lunar calendar")
#let abstractContent = "This document defines the Hijri week calendar (HWC) which is a Hijri counterpart of the ISO 8601 calendar. Dates generated by this calendar are referred to as Hijri week dates (HWD). Since Hijri calendars are lunar calendars, it was necessary to define a standard counterpart to the ISO 8601 calendar tailored to the unique aspects of Hijri calendars while aligning with the fundamental principles of the ISO 8601 calendar."

#let publishDate = datetime(year: 2024, month: 01, day: 15)

#let abstract = (
    (title: "Abstract", content: abstractContent),
  )

#let authors = (
  (
    name: "Mohsen Alyafie",
    // orcid: "0000-0002-7859-8394",
    email: "malshayef@gmail.com",
    affiliations: "1"
  ),
  (
    name: "Bekkai Amine Fatah",
    // orcid: "0000-0002-7859-8394",
    email: "biz.afatah@gmail.com",
    affiliations: "2"
  ),
)

#let affiliations = (
   (id: "1", name: "Qatar Airways"),
   (id: "2", name: "Zaman"),
  )

#let margins = (
    (
      title: "Correspondence to",
      content: [
        Mohsen Alyafie\
        #link("mailto:malshayef@gmail.com")[malshayef\@gmail.com]\

        Bekkai Amine Fatah
        #link("mailto:biz.afatah@gmail.com")[biz.afatah\@gmail.com]
      ],
    ),
    (
      title: "Data Availability",
      content: [
        A working implementation for the Javascript Temporal object can be found and used on #link("https://github.com/khawarizmus/hijri-week-calendar")[GitHub].
      ],
    ),
  )